# Generated by Django 5.1.4 on 2025-01-08 22:38

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FileField(upload_to=post.models.upload_to),
        ),
    ]
